USE ROLE ACCOUNTADMIN;
USE DATABASE SALES_DB;

CREATE OR REPLACE SCHEMA ANALYTICS;

USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY NUMBER AUTOINCREMENT,
  CUSTOMER_ID STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_KEY NUMBER AUTOINCREMENT,
  PRODUCT_ID STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY NUMBER,          -- YYYYMMDD
  ORDER_DATE DATE,
  YEAR NUMBER,
  MONTH NUMBER,
  DAY NUMBER
);

CREATE OR REPLACE TABLE FACT_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_KEY NUMBER,
  PRODUCT_KEY NUMBER,
  DATE_KEY NUMBER,
  QUANTITY NUMBER,
  PAYMENT_METHOD STRING,
  LOAD_TIME TIMESTAMP_NTZ
);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID)
SELECT DISTINCT CUSTOMER_ID
FROM RAW.target_table_orders t
WHERE CUSTOMER_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM DIM_CUSTOMER d WHERE d.CUSTOMER_ID = t.CUSTOMER_ID
  );

INSERT INTO DIM_PRODUCT (PRODUCT_ID)
SELECT DISTINCT PRODUCT_ID
FROM RAW.target_table_orders t
WHERE PRODUCT_ID IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM DIM_PRODUCT p WHERE p.PRODUCT_ID = t.PRODUCT_ID
  );


INSERT INTO DIM_DATE (DATE_KEY, ORDER_DATE, YEAR, MONTH, DAY)
SELECT DISTINCT
  TO_NUMBER(TO_CHAR(CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
  CREATED_AT::DATE AS ORDER_DATE,
  YEAR(CREATED_AT::DATE),
  MONTH(CREATED_AT::DATE),
  DAY(CREATED_AT::DATE)
FROM RAW.target_table_orders t
WHERE CREATED_AT IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM DIM_DATE d WHERE d.ORDER_DATE = t.CREATED_AT::DATE
  );


INSERT INTO FACT_ORDERS (
  ORDER_ID, CUSTOMER_KEY, PRODUCT_KEY, DATE_KEY,
  QUANTITY, PAYMENT_METHOD, LOAD_TIME
)
SELECT
  t.ORDER_ID,
  c.CUSTOMER_KEY,
  p.PRODUCT_KEY,
  TO_NUMBER(TO_CHAR(t.CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
  t.QUANTITY,
  t.PAYMENT_METHOD,
  t.LOAD_TIME
FROM RAW.target_table_orders t
JOIN DIM_CUSTOMER c ON t.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID
WHERE t.CREATED_AT IS NOT NULL;



--# Automated Task -- 

CREATE OR REPLACE TASK analytics_build_task
WAREHOUSE = TRANSFORM_WH
SCHEDULE = '30 MINUTE'
AS
    BEGIN
  -- Load dimensions
         INSERT INTO ANALYTICS.DIM_CUSTOMER (CUSTOMER_ID)
            SELECT DISTINCT CUSTOMER_ID
            FROM RAW.target_table_orders t
            WHERE CUSTOMER_ID IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM ANALYTICS.DIM_CUSTOMER d WHERE                   d.CUSTOMER_ID=t.CUSTOMER_ID);

         INSERT INTO ANALYTICS.DIM_PRODUCT (PRODUCT_ID)
            SELECT DISTINCT PRODUCT_ID
            FROM RAW.target_table_orders t
            WHERE PRODUCT_ID IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM ANALYTICS.DIM_PRODUCT p WHERE                    p.PRODUCT_ID=t.PRODUCT_ID);

         INSERT INTO ANALYTICS.DIM_DATE (DATE_KEY, ORDER_DATE, YEAR, MONTH,                                           DAY)
            SELECT DISTINCT
            TO_NUMBER(TO_CHAR(CREATED_AT::DATE, 'YYYYMMDD')),
            CREATED_AT::DATE,
            YEAR(CREATED_AT::DATE),
            MONTH(CREATED_AT::DATE),
            DAY(CREATED_AT::DATE)
            FROM RAW.target_table_orders t
            WHERE CREATED_AT IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM ANALYTICS.DIM_DATE d WHERE                     d.ORDER_DATE=t.CREATED_AT::DATE);

  -- Load Fact
         INSERT INTO ANALYTICS.FACT_ORDERS
            SELECT
            t.ORDER_ID,
            c.CUSTOMER_KEY,
            p.PRODUCT_KEY,
            TO_NUMBER(TO_CHAR(t.CREATED_AT::DATE, 'YYYYMMDD')),
            t.QUANTITY,
            t.PAYMENT_METHOD,
            t.LOAD_TIME
            FROM RAW.target_table_orders t
            JOIN ANALYTICS.DIM_CUSTOMER c ON t.CUSTOMER_ID = c.CUSTOMER_ID
            JOIN ANALYTICS.DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID
            WHERE t.CREATED_AT IS NOT NULL;
    END;


ALTER TASK analytics_build_task RESUME;

