// Using Streams + MERGE + Tasks
// step 4 is building analytics tables, Step 5 will ensure:->
-- dims/facts update automatically.
-- no duplicates.
-- late-arriving data handled.
-- incremental processing (not full reload).

USE ROLE ACCOUNTADMIN;
USE DATABASE SALES_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STREAM target_orders_stream
ON TABLE target_table_orders
APPEND_ONLY = TRUE;


USE SCHEMA ANALYTICS;

MERGE INTO DIM_CUSTOMER d    // MERGE DIM_CUSTOMER
USING (
  SELECT DISTINCT CUSTOMER_ID
  FROM RAW.target_orders_stream
  WHERE CUSTOMER_ID IS NOT NULL
) s
ON d.CUSTOMER_ID = s.CUSTOMER_ID
WHEN NOT MATCHED THEN
  INSERT (CUSTOMER_ID) VALUES (s.CUSTOMER_ID);

  
MERGE INTO DIM_PRODUCT d   // MERGE DIM_PRODUCT
USING (
  SELECT DISTINCT PRODUCT_ID
  FROM RAW.target_orders_stream
  WHERE PRODUCT_ID IS NOT NULL
) s
ON d.PRODUCT_ID = s.PRODUCT_ID
WHEN NOT MATCHED THEN
  INSERT (PRODUCT_ID) VALUES (s.PRODUCT_ID);


MERGE INTO DIM_DATE d   // MERGE DIM_DATE
USING (
  SELECT DISTINCT
    TO_NUMBER(TO_CHAR(CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
    CREATED_AT::DATE AS ORDER_DATE,
    YEAR(CREATED_AT::DATE) AS YEAR,
    MONTH(CREATED_AT::DATE) AS MONTH,
    DAY(CREATED_AT::DATE) AS DAY
  FROM RAW.target_orders_stream
  WHERE CREATED_AT IS NOT NULL
) s
ON d.DATE_KEY = s.DATE_KEY
WHEN NOT MATCHED THEN
  INSERT (DATE_KEY, ORDER_DATE, YEAR, MONTH, DAY)
  VALUES (s.DATE_KEY, s.ORDER_DATE, s.YEAR, s.MONTH, s.DAY);


-- Testing logic 
MERGE INTO FACT_ORDERS f
USING (
  SELECT
    t.ORDER_ID,
    c.CUSTOMER_KEY,
    p.PRODUCT_KEY,
    TO_NUMBER(TO_CHAR(t.CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
    t.QUANTITY,
    t.PAYMENT_METHOD,
    t.LOAD_TIME
  FROM RAW.target_orders_stream t
  JOIN DIM_CUSTOMER c ON t.CUSTOMER_ID = c.CUSTOMER_ID
  JOIN DIM_PRODUCT  p ON t.PRODUCT_ID = p.PRODUCT_ID
  WHERE t.CREATED_AT IS NOT NULL
) s
ON f.ORDER_ID = s.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_KEY    = s.CUSTOMER_KEY,
  PRODUCT_KEY     = s.PRODUCT_KEY,
  DATE_KEY        = s.DATE_KEY,
  QUANTITY        = s.QUANTITY,
  PAYMENT_METHOD  = s.PAYMENT_METHOD,
  LOAD_TIME       = s.LOAD_TIME
WHEN NOT MATCHED THEN
  INSERT (ORDER_ID, CUSTOMER_KEY, PRODUCT_KEY, DATE_KEY, QUANTITY, PAYMENT_METHOD, LOAD_TIME)
  VALUES (s.ORDER_ID, s.CUSTOMER_KEY, s.PRODUCT_KEY, s.DATE_KEY, s.QUANTITY, s.PAYMENT_METHOD, s.LOAD_TIME);



-- Automated logic which is tested in privious step
CREATE OR REPLACE TASK analytics_incremental_task
WAREHOUSE = TRANSFORM_WH
SCHEDULE = '10 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.TARGET_ORDERS_STREAM')
AS
BEGIN
  -- Dimensions
  MERGE INTO ANALYTICS.DIM_CUSTOMER d
  USING (
    SELECT DISTINCT CUSTOMER_ID
    FROM RAW.TARGET_ORDERS_STREAM
    WHERE CUSTOMER_ID IS NOT NULL
  ) s
  ON d.CUSTOMER_ID = s.CUSTOMER_ID
  WHEN NOT MATCHED THEN
    INSERT (CUSTOMER_ID) VALUES (s.CUSTOMER_ID);

  MERGE INTO ANALYTICS.DIM_PRODUCT d
  USING (
    SELECT DISTINCT PRODUCT_ID
    FROM RAW.TARGET_ORDERS_STREAM
    WHERE PRODUCT_ID IS NOT NULL
  ) s
  ON d.PRODUCT_ID = s.PRODUCT_ID
  WHEN NOT MATCHED THEN
    INSERT (PRODUCT_ID) VALUES (s.PRODUCT_ID);

  MERGE INTO ANALYTICS.DIM_DATE d
  USING (
    SELECT DISTINCT
      TO_NUMBER(TO_CHAR(CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
      CREATED_AT::DATE AS ORDER_DATE,
      YEAR(CREATED_AT::DATE) AS YEAR,
      MONTH(CREATED_AT::DATE) AS MONTH,
      DAY(CREATED_AT::DATE) AS DAY
    FROM RAW.TARGET_ORDERS_STREAM
    WHERE CREATED_AT IS NOT NULL
  ) s
  ON d.DATE_KEY = s.DATE_KEY
  WHEN NOT MATCHED THEN
    INSERT (DATE_KEY, ORDER_DATE, YEAR, MONTH, DAY)
    VALUES (s.DATE_KEY, s.ORDER_DATE, s.YEAR, s.MONTH, s.DAY);

  -- Fact
  MERGE INTO ANALYTICS.FACT_ORDERS f
  USING (
    SELECT
      t.ORDER_ID,
      c.CUSTOMER_KEY,
      p.PRODUCT_KEY,
      TO_NUMBER(TO_CHAR(t.CREATED_AT::DATE, 'YYYYMMDD')) AS DATE_KEY,
      t.QUANTITY,
      t.PAYMENT_METHOD,
      t.LOAD_TIME
    FROM RAW.TARGET_ORDERS_STREAM t
    JOIN ANALYTICS.DIM_CUSTOMER c ON t.CUSTOMER_ID = c.CUSTOMER_ID
    JOIN ANALYTICS.DIM_PRODUCT  p ON t.PRODUCT_ID = p.PRODUCT_ID
    WHERE t.CREATED_AT IS NOT NULL
  ) s
  ON f.ORDER_ID = s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET
    CUSTOMER_KEY    = s.CUSTOMER_KEY,
    PRODUCT_KEY     = s.PRODUCT_KEY,
    DATE_KEY        = s.DATE_KEY,
    QUANTITY        = s.QUANTITY,
    PAYMENT_METHOD  = s.PAYMENT_METHOD,
    LOAD_TIME       = s.LOAD_TIME
  WHEN NOT MATCHED THEN
    INSERT (ORDER_ID, CUSTOMER_KEY, PRODUCT_KEY, DATE_KEY, QUANTITY, PAYMENT_METHOD, LOAD_TIME)
    VALUES (s.ORDER_ID, s.CUSTOMER_KEY, s.PRODUCT_KEY, s.DATE_KEY, s.QUANTITY, s.PAYMENT_METHOD, s.LOAD_TIME);
END;


ALTER TASK analytics_incremental_task RESUME; // start the task


  
