USE ROLE ACCOUNTADMIN;
-- Create Roles --
CREATE OR REPLACE ROLE DATA_ENGINEER;
CREATE OR REPLACE ROLE DATA_ANALYST;

-- Assign Roles to SYSADMIN (role hierarchy) --

GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYST TO ROLE SYSADMIN;

// Engineer needs ingest + transform warehouses

GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER;

 // Analyst only needs reporting

 GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE DATA_ANALYST;

 // Engineer access (RAW + ANALYTICS)
 GRANT USAGE ON DATABASE SALES_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA SALES_DB.RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA SALES_DB.ANALYTICS TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALES_DB.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALES_DB.ANALYTICS TO ROLE DATA_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.ANALYTICS TO ROLE DATA_ENGINEER;

-- Analyst Access using Secure Views --

// Give schema usage only for analytics

GRANT USAGE ON DATABASE SALES_DB TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA SALES_DB.ANALYTICS TO ROLE DATA_ANALYST;

//Create Secure Views for Analysts
USE ROLE DATA_ENGINEER;
USE DATABASE SALES_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE SECURE VIEW VW_ORDER_SUMMARY AS
SELECT
  DATE_KEY,
  PAYMENT_METHOD,
  COUNT(*) AS TOTAL_ORDERS,
  SUM(QUANTITY) AS TOTAL_QTY
FROM FACT_ORDERS
GROUP BY 1,2;

// grant access on views 
GRANT SELECT ON VIEW SALES_DB.ANALYTICS.VW_ORDER_SUMMARY TO ROLE DATA_ANALYST;


-- Testing RBAC access --

// Test as Analyst
USE ROLE DATA_ANALYST;

SELECT * FROM SALES_DB.ANALYTICS.VW_ORDER_SUMMARY;   -- should work 
SELECT * FROM SALES_DB.RAW.STG_ORDERS_LANDING;       -- should fail 

// Test as Engineer
USE ROLE DATA_ENGINEER;

SELECT * FROM SALES_DB.RAW.STG_ORDERS_LANDING;       -- should work 
SELECT * FROM SALES_DB.ANALYTICS.FACT_ORDERS;        -- should work 
