use role accountadmin;


// Warehouse Cost Control (Auto Suspend/Resume)
ALTER WAREHOUSE INGEST_WH SET 
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

ALTER WAREHOUSE TRANSFORM_WH SET 
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE;

ALTER WAREHOUSE REPORTING_WH SET 
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

// Add Resource Monitor
  CREATE OR REPLACE RESOURCE MONITOR sales_rm
WITH CREDIT_QUOTA = 50
FREQUENCY = MONTHLY
TRIGGERS
  ON 80 PERCENT DO NOTIFY
  ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE INGEST_WH SET RESOURCE_MONITOR = sales_rm;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = sales_rm;
ALTER WAREHOUSE REPORTING_WH SET RESOURCE_MONITOR = sales_rm; //Attach to warehouses


// most expensive queries (credits/time)

SELECT
  QUERY_ID,
  USER_NAME,
  WAREHOUSE_NAME,
  TOTAL_ELAPSED_TIME/1000 AS seconds,
  BYTES_SCANNED/1024/1024 AS mb_scanned,
  QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('DAY', -1, CURRENT_TIMESTAMP())
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 10;

